## ***1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns***

In [7]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T

# Print the original and transposed arrays
print("Original Array:")
print(array_3x3)
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[19 80 21]
 [34 92  2]
 [40  4 92]]

Transposed Array:
[[19 34 40]
 [80 92  4]
 [21  2 92]]


## ***2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.***

In [8]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Generates an array with elements from 0 to 9

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Output the arrays
print("1D Array:")
print(array_1d)
print("\nReshaped 2x5 Array:")
print(array_2x5)
print("\nReshaped 5x2 Array:")
print(array_5x2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## ***3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array***

In [9]:

import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)  # Generates a 4x4 array with values between 0 and 1

# Step 2: Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Output the original and bordered arrays
print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.13141405 0.4702703  0.6041058  0.41088755]
 [0.6325553  0.42226466 0.13657723 0.62153728]
 [0.00402444 0.65136272 0.00862696 0.16903453]
 [0.98262177 0.15324947 0.66249318 0.68252846]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.13141405 0.4702703  0.6041058  0.41088755 0.        ]
 [0.         0.6325553  0.42226466 0.13657723 0.62153728 0.        ]
 [0.         0.00402444 0.65136272 0.00862696 0.16903453 0.        ]
 [0.         0.98262177 0.15324947 0.66249318 0.68252846 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## **4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [10]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_step_5 = np.arange(10, 61, 5)

# Output the array
print("Array of integers from 10 to 60 with a step of 5:")
print(array_step_5)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


## **5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**


In [11]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)    # Uppercase
lowercase_array = np.char.lower(string_array)    # Lowercase
titlecase_array = np.char.title(string_array)     # Title Case
capitalize_array = np.char.capitalize(string_array)  # Capitalize

# Output the original and transformed arrays
print("Original Array:")
print(string_array)

print("\nUppercase Array:")
print(uppercase_array)

print("\nLowercase Array:")
print(lowercase_array)

print("\nTitle Case Array:")
print(titlecase_array)

print("\nCapitalized Array:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']

Capitalized Array:
['Python' 'Numpy' 'Pandas']


## **6.Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [12]:
import numpy as np

# Create a NumPy array of words
word_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', word_array)

# Output the transformed array
print("Original Array:")
print(word_array)

print("\nArray with spaces between characters:")
print(spaced_array)


Original Array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


##*** 7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.***

In [13]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition_result = array1 + array2

# Perform element-wise subtraction
subtraction_result = array1 - array2

# Perform element-wise multiplication
multiplication_result = array1 * array2

# Perform element-wise division
division_result = array1 / array2

# Output the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## ***8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.***

In [14]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Output the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


## ***9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.***

In [15]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Step 2: Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

random_integers, prime_numbers


(array([188, 164, 905, 342, 107, 753, 548, 130, 615, 451,  48, 301, 154,
        881,  49, 298, 913, 806, 896, 489, 747, 144, 238,  13, 998, 987,
        319, 945, 945, 690, 345, 216, 225, 111, 294, 775, 550, 549, 809,
          0,  77, 256, 637, 963, 316, 266, 967, 870, 925, 154, 812, 975,
        624, 325, 164, 380, 373, 350, 536, 356, 108, 765, 592, 154, 805,
        321, 516, 165, 562, 474, 172, 136, 991, 441, 712, 364, 389, 158,
        476,  32, 575, 483, 890, 499, 983, 510, 974, 714, 622, 144, 234,
        152, 410, 343, 271, 160, 896, 866, 797, 741]),
 [107, 881, 13, 809, 967, 373, 991, 389, 499, 983, 271, 797])

## ***10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.***


In [16]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, let's generate random temperatures between 20 and 35 degrees Celsius.
daily_temperatures = np.random.uniform(20, 35, size=30)

# Step 2: Reshape the array into a 4-week format (each week has 7 days)
# We will pad with NaN values to handle the extra days if needed (for 30 days).
# 4 complete weeks and 2 extra days will be reshaped to (4, 7).
weeks_temperatures = np.pad(daily_temperatures, (0, 7 - (len(daily_temperatures) % 7)), mode='constant', constant_values=np.nan)
weeks_temperatures = weeks_temperatures.reshape(-1, 7)

# Step 3: Calculate weekly averages, ignoring NaN values
weekly_averages = np.nanmean(weeks_temperatures, axis=1)

# Output the daily temperatures and weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[23.86385088 25.2380919  23.41025084 27.0444817  23.477147   26.01628135
 31.98177828 31.24392428 31.84016388 32.91581812 20.88387974 31.24468835
 26.84016896 30.76076439 21.48778366 28.31544772 33.92904638 33.98013555
 32.49150511 28.73083091 23.22879821 20.47009224 30.52597744 24.52473243
 34.78873565 27.30444461 25.64124719 29.26505631 31.75402676 32.12500401]

Weekly Averages:
[25.86169742 29.38991539 28.88050679 27.50289798 31.93951539]
